### ISSUE TITLE
Issue when you enter first a letter

### ISSUE THREAD

**Issue by rodriguezmanu** [nitishkumarsingh13/Angularjs-Directive-Accept-Number-Only#1]
When you enter a letter first looks like enter in a infinite loop and doesn't work.
I think the issue is in render.
 if (isNaN(newValue)) {
                  ngModel.$setViewValue(oldValue);
                  ngModel.$render();
                }
I'll try to fix it.
Thanks in advance

**Comment by asafz83** [comment]
From what I see - changing it to:

if (isNaN(newValue)) {
ngModel.$setViewValue(oldValue || '');
ngModel.$render();
}

solves the issue

**Comment by nitishk1316** [comment]
This issue is fixed now.

Thanks @asafz83
