### ISSUE TITLE
decimal-upto="5" is not working. It is working for decimal-upto="3"

### ISSUE THREAD

**Issue by abhiram90** [nitishkumarsingh13/Angularjs-Directive-Accept-Number-Only#2]
This directive is working great for decimal-upto="2" and decimal-upto="3". When I tried to use decimal-upto="5" it is not working. Is this feature missing for number n? If so please add that feature also.

**Comment by nitishk1316** [comment]
@abhiram90 

I tested it.
It is working fine.
Can you give some more details about this bug

**Comment by nitishk1316** [comment]
It is working fine.
